// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgdcIhWFuSXV1SLo6tGU-UD1DT082PT5M',
    appId: '1:312864139657:android:8cd0dd34b67563f66d5958',
    messagingSenderId: '312864139657',
    projectId: 'e-commerce-flutter-f7d0b',
    storageBucket: 'e-commerce-flutter-f7d0b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQ1RcmFnZy2ybfgtYIraY6KjhQGHRuI6Y',
    appId: '1:312864139657:ios:32968dab4a31fdb56d5958',
    messagingSenderId: '312864139657',
    projectId: 'e-commerce-flutter-f7d0b',
    storageBucket: 'e-commerce-flutter-f7d0b.appspot.com',
    androidClientId: '312864139657-7bl56p89ctbosbeobsfqlph59fk6j5mt.apps.googleusercontent.com',
    iosClientId: '312864139657-egv8km9mhg8jgvrqr0ak45mbbo65k8eh.apps.googleusercontent.com',
    iosBundleId: 'com.wagdyBuild.ecommerce',
  );
}
